package com.game.roundr.models;

public enum MessageType {
	CONNECT, CONNECT_OK, CONNECT_FAILED, USER_JOINED, USER_LIST, READY, DISCONNECT, KICK, BAN, CHAT, START_GAME, END_GAME, RANDOM_WORD, PLAYER_SCORE
}
